function SVMModel = detectAIGeneratedTextNew()
% Example training datasets
humanTexts = {
    'This is a sample human-written text.', 
    'Another example of human text for testing.', 
    'Humans write in a varied and expressive way.'
};

aiTexts = {
    'This text was generated by an AI.', 
    'AI-generated content can be quite convincing.', 
    'Here is an example of a text that was generated by an AI model.'
};
% Extract features for both datasets
humanFeatures = extractFeatures(humanTexts);
aiFeatures = extractFeatures(aiTexts);

% Combine features and create labels
features = [humanFeatures; aiFeatures];
labels = [zeros(size(humanFeatures, 1), 1); ones(size(aiFeatures, 1), 1)]; % 0 for human, 1 for AI

% Train a classifier
SVMModel = fitcsvm(features, labels, 'KernelFunction', 'linear', 'Standardize', true);

end

% % Loop to get user input and classify new texts
% while true
%     % Prompt user to enter a new text
%     newText = input('Enter a text to classify (or type "exit" to quit): ', 's');
%     
%     % Exit condition
%     if strcmpi(newText, 'exit')
%         break;
%     end
%     
%     % Classify the new text
%     predictedLabel = classifyNewText(SVMModel, newText);
%     
%     % Display the result
%     fprintf('Text: %s\n', newText);
%     if predictedLabel == 1
%         fprintf('Predicted: AI-generated\n\n');
%     else
%         fprintf('Predicted: Human-written\n\n');
%     end
% end
% 
% fprintf('Exiting the text classification.\n');
